name: Deploy back-rds

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'backend_rds/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Determine Version Tag
        id: version
        run: |
          TAG=$(git describe --tags --always --dirty)
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Log-in to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push backend_rds Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE_TAG: ${{ env.tag }}
        run: |
          cd backend_rds
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/rds-api-repo:$IMAGE_TAG .
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/rds-api-repo:$IMAGE_TAG
        
      - name: Update ECS service for backend_rds
        run: |
          # Отримуємо поточний task_definition
          TASK_DEF=$(aws ecs describe-task-definition --task-definition rds_api_task --region $AWS_REGION)

          # Замінюємо тег образу в task_definition
          NEW_TASK_DEF=$(echo $TASK_DEF | jq '.taskDefinition | {containerDefinitions, family, executionRoleArn, taskRoleArn, networkMode, requiresCompatibilities, cpu, memory}')
          NEW_TASK_DEF=$(echo $NEW_TASK_DEF | jq '.containerDefinitions[0].image = "'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/rds-api-repo:'$IMAGE_TAG'"')

          # Зберігаємо новий task_definition у тимчасовий файл
          echo $NEW_TASK_DEF > new-task-def.json

          # Реєструємо новий task_definition
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --region $AWS_REGION | jq -r '.taskDefinition.taskDefinitionArn')

          # Оновлюємо ECS-сервіс з новою ревізією task_definition
          aws ecs update-service --cluster api-cluster --service rds_api_service --task-definition $NEW_TASK_DEF_ARN --region $AWS_REGION --force-new-deployment