name: Deploy back-rds manual

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Validate input - only tags allowed
        run: |
          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
            echo "Error: This workflow can only be triggered with a tag, not a branch."
            exit 1
          fi
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true

      - name: Determine Tag
        id: determine_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Using tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Log-in to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push backend_rds Image
        run: |
         
          echo "RUN"
